Update SConscript
The linker flag -lsubunit is needed to resolve an undefined reference to 'subunit_test_XXX' at this point. This is not an issue with libcheck